import sqlite3


conn = sqlite3.connect('banco.db', check_same_thread=False)

criar_tabelas =  '''
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INTEGER PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    SENHA TEXT NOT NULL,
        ON DELETE CASCADE
        ON UPDATE CASCADE;
);

CREATE TABLE IF NOT EXISTS TAREFA (
    ID INTEGER,
    NOME TEXT NOT NULL,
    DESCRICAO TEXT,
    TIPO_ID INTEGER NOT NULL,
    STATUS_ID INTEGER NOT NULL,
    PRIORIDADE_ID INTEGER NOT NULL,
    USUARIO_ID INTEGER  NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    DATA_TERMINO DATE,
    DATA_PREVISTA DATE
    PRIMARY KEY (ID, TIPO_ID, STATUS_ID, PRIORIDADE_ID, USUARIO_ID),
    FOREIGN KEY(TIPO_ID)
        REFERENCES TIPO(ID_TIPO)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY(STATUS_ID)
        REFERENCES STATUS(ID_STATUS)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY(PRIORIDADE_ID)
        REFERENCES PRIORIDADE(ID_PRIORIDADE)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY(USUARIO_ID) 
        REFERENCES USUARIO(ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TIPO (
    ID_TIPO INTEGER PRIMARY KEY,
    NOME TEXT,
    USUARIO_ID INTEGER
    FOREIGN KEY(USUARIO_ID) 
        REFERENCES USUARIO(ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS STATUS (
    ID_STATUS INTEGER PRIMARY KEY,
    NOME TEXT,
        ON DELETE CASCADE
        ON UPDATE CASCADE;
);

CREATE TABLE IF NOT EXISTS PRIORIDADE (
    ID_PRIORIDADE INTEGER PRIMARY KEY,
    NOME TEXT,
        ON DELETE CASCADE
        ON UPDATE CASCADE;
);
'''

conn.commit()